server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password123
    key-store-type: PKCS12
    key-alias: your-key-alias
  error:
    include-message: always

spring:
  profiles:
    active: default
  application:
    name: Logisight
  autoconfigure:
    exclude:
      - org.springframework.ai.vectorstore.redis.autoconfigure.RedisVectorStoreAutoConfiguration
      
  datasource:
    url: jdbc:postgresql://localhost:5058/argusdb
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true 
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

 

  main:
    allow-circular-references: true

security:
  jwt:
    secret: "tHb7G#eR2jP@Lkd88zQs9xVnTf^uYmWpAk&cEe34Kd^Mv$NxC8wT!bLpGsQz@9VdPxR7KeLzUc#XyTfNqD7VfW^9ZqMx"
    expiration: 3600000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.security: DEBUG


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    
    management:
  endpoints:
    web:
      exposure:
        include: []